name: TradeAuditing
author: CodingAir
version: "${project.version}"
description: Audit trades with ease.
main: de.codingair.tradesystem.ext.auditing.TradeAuditing
depend: [TradeSystem]
load-after: [TradeSystem]

api-version: "1.13"