name: TradeAudit
author: CodingAir
version: "${project.version}"
description: Audit trades with ease.
main: de.codingair.tradesystem.ext.audit.TradeAudit
depend: [TradeSystem]
load-after: [TradeSystem]

api-version: "1.13"

permissions:
  tradesystem.audit.updates.notify:
    default: op
    description: "Notify admins when a new update is available."
  tradesystem.audit.notify:
    default: op
    description: "Notify admins when players start a trade."
  tradesystem.audit.start:
    default: op
    description: "Enable admins to use the /audit command."