name: TradeAudit
author: CodingAir
version: "${project.version}"
description: Audit trades with ease.
main: de.codingair.tradesystem.ext.audit.TradeAudit
depend: [TradeSystem]
load-after: [TradeSystem]

api-version: "1.13"

permissions:
  tradesystem.auditing.notify:
    default: op