name: TradeAudit
author: CodingAir
version: "${project.version}"
description: Audit trades with ease.
main: de.codingair.tradesystem.ext.audit.TradeAudit
depend: [TradeSystem]
softdepend: [MMOItems]
load-after: [TradeSystem]

api-version: "1.13"

permissions:
  tradesystem.audit.updates.notify:
    default: op
    description: "Notify admins when a new update is available."
  tradesystem.audit.notify:
    default: op
    description: "Notify admins when players start a trade."
  tradesystem.audit.start:
    default: op
    description: "Enable admins to use the /audit command."
  tradesystem.audit.stats:
    default: op
    description: "Enable admins to use the /tradelog command."
  tradesystem.audit.*:
    default: op
    description: "Enable admins to use all futures."
    children:
      tradesystem.audit.notify: true
      tradesystem.audit.start: true
      tradesystem.audit.stats: true
      tradesystem.audit.updates.notify: true